# Generated by Django 5.0.7 on 2025-04-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_mentorprofile_college_zoommeeting'),
        ('students', '0017_alter_projectcomment_author_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('watchers', models.IntegerField(default=0)),
                ('contributors', models.JSONField(default=dict)),
                ('languages', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_stats', to='students.project')),
            ],
        ),
    ]
