# Generated by Django 5.0.7 on 2025-04-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabrators', '0002_remove_collaboratorprofile_expertise_areas_and_more'),
        ('students', '0007_alter_project_student_groupmembership_studentgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCollaboratorSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.TextField(blank=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to='collabrators.collaboratorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_shares', to='students.project')),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('project', 'collaborator')},
            },
        ),
    ]
