# Generated by Django 5.0.7 on 2025-04-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_projectcollaboratorsharing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCollaboratorSharing',
        ),
    ]
