# Generated by Django 5.0.7 on 2025-04-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabrators', '0003_alter_collaboratorprofile_options_and_more'),
        ('students', '0010_project_is_open_for_collaboration_projectcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='collaborator',
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author_collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='collabrators.collaboratorprofile'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='students.projectcomment'),
        ),
    ]
