# Generated by Django 5.0.7 on 2025-04-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_projectcomment_collaborator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='college',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_feedback',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_grade',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_file',
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='students.studentgroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sdgs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('on_hold', 'On Hold')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('on_hold', 'On Hold')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='students.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
