# Generated by Django 5.0.7 on 2025-04-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_mentorprofile_college_zoommeeting'),
        ('students', '0012_remove_project_collaborator_remove_project_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to='mentor.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sdgs',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('on_hold', 'On Hold')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectstatusupdate',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('on_hold', 'On Hold')], max_length=20),
        ),
    ]
