# Generated by Django 5.0.7 on 2025-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_project_group_project_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatusupdate',
            name='updated_by_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
