# Generated by Django 5.0.7 on 2025-04-13 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_ngo'),
        ('mentor', '0004_alter_mentorprofile_college_zoommeeting'),
        ('students', '0014_projectstatusupdate_updated_by_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_projects', to='college.collegeprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_projects', to='students.studentgroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_projects', to='mentor.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sdgs',
            field=models.CharField(help_text='Sustainable Development Goals', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Technologies used', max_length=500),
        ),
        migrations.DeleteModel(
            name='ProjectStatusUpdate',
        ),
    ]
