# Generated by Django 5.0.7 on 2025-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_project_collaborator_project_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='author_collaborator',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='author_student',
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author_type',
            field=models.CharField(choices=[('student', 'Student'), ('collaborator', 'Collaborator')], default='student', max_length=20),
        ),
    ]
