# Generated by Django 5.0.7 on 2025-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_remove_projectcomment_author_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='author_type',
            field=models.CharField(choices=[('student', 'Student'), ('collaborator', 'Collaborator')], max_length=20),
        ),
    ]
