# Generated by Django 5.0.7 on 2025-04-25 15:45

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_projectassessment_delete_collegeactivity'),
        ('students', '0017_alter_projectcomment_author_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, help_text='Project image 1', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, help_text='Project image 2', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, help_text='Project image 3', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, help_text='Project image 4', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.ImageField(blank=True, help_text='Project image 5', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image6',
            field=models.ImageField(blank=True, help_text='Project image 6', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image1',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Project Image 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Project Image 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image3',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Project Image 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image4',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Project Image 4'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image5',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Project Image 5'),
        ),
        migrations.AlterField(
            model_name='project',
            name='college',
            field=models.ForeignKey(blank=True, default=students.models.get_default_college, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_projects', to='college.collegeprofile'),
        ),
    ]
