# Generated by Django 5.0.7 on 2025-04-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_project_image1_project_image2_project_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image6',
        ),
    ]
