# Generated by Django 5.0.7 on 2025-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabrators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='expertise_areas',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='collaborator_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student Collaborator'), ('EXPERT', 'Industry Expert')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile Development'), ('AI', 'Artificial Intelligence'), ('DATA', 'Data Science'), ('CLOUD', 'Cloud Computing'), ('CYBER', 'Cybersecurity'), ('IOT', 'Internet of Things'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='industry_certifications',
            field=models.TextField(blank=True, help_text='List your relevant certifications', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CollaborationRequest',
        ),
    ]
