# Generated by Django 5.0.7 on 2025-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabrators', '0002_remove_collaboratorprofile_expertise_areas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboratorprofile',
            options={'verbose_name': 'Collaborator Profile', 'verbose_name_plural': 'Collaborator Profiles'},
        ),
        migrations.RenameField(
            model_name='collaboratorprofile',
            old_name='github_profile',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='collaboratorprofile',
            old_name='linkedin_profile',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='collaboratorprofile',
            old_name='portfolio_website',
            new_name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='collaborator_type',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='industry_certifications',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
