# Generated by Django 5.0.7 on 2025-04-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabrators', '0004_zoommeeting'),
        ('students', '0017_alter_projectcomment_author_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=200)),
                ('meeting_description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('zoom_link', models.URLField()),
                ('zoom_meeting_id', models.CharField(max_length=200)),
                ('zoom_password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabrators.collaboratorprofile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.project')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.DeleteModel(
            name='ZoomMeeting',
        ),
    ]
