# Generated by Django 5.0.7 on 2025-04-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('assessment', 'Assessment'), ('review', 'Project Review'), ('presentation', 'Presentation'), ('submission', 'Submission Deadline'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('target_semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=2)),
                ('target_branch', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('online_meeting_link', models.URLField(blank=True, null=True)),
                ('assessment_criteria', models.TextField(blank=True, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='college_activities/')),
                ('submission_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='college.collegeprofile')),
            ],
            options={
                'verbose_name': 'College Activity',
                'verbose_name_plural': 'College Activities',
                'ordering': ['-start_date'],
            },
        ),
    ]
